import type { Metadata } from 'next';
import { Saira, Saira_Condensed } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header/Header';

const saira = Saira({
   subsets: ['latin'],
   variable: '--font-saira',
   weight: ['400', '700'],
});

const sairaCondensed = Saira_Condensed({
   subsets: ['latin'],
   variable: '--font-saira-condensed',
   weight: ['400', '700'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const navigationItems = [
      { label: 'HABERLER', href: '#haberler' },
      { label: 'ETKİNLİKLER', href: '#etkinlikler' },
      { label: 'MÜZİKLER', href: '#muzikler' },
      { label: 'VİDEOLAR', href: '#videolar' },
      { label: 'BLOG', href: '/blog' },
      { label: 'İLETİŞİM', href: '#iletisim' },
   ];

   return (
      <html lang="en">
         <body className={`${saira.variable} ${sairaCondensed.variable} font-sans`}>
            <Header navigationItems={navigationItems} />
            <main>{children}</main>
         </body>
      </html>
   );
}
